import assert from "node:assert/strict";
import {existsSync, readFileSync} from "node:fs";

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
assert.equal(existsSync(new URL("../app/clips/[id]/page.tsx", import.meta.url)), true, "dynamic clip route exists");
assert.equal(existsSync(new URL("../app/creators/[slug]/page.tsx", import.meta.url)), true, "dynamic creator route exists");
const clipDetail = read("components/clip-detail.tsx");
assert.match(clipDetail, /CopyPrompt/);
assert.match(clipDetail, /aria-expanded/);
const media = read("components/adaptive-media.tsx");
for (const ratio of ["9:16", "4:5", "1:1", "16:9", "2:1", "2.39:1"]) assert.match(media, new RegExp(ratio.replace(".", "\\.")));
assert.match(media, /IntersectionObserver/);
assert.match(media, /visibilitychange/);
assert.match(media, /activePreview/);
assert.match(media, /prefers-reduced-motion/);
assert.match(media, /previewActive/);
assert.match(media, /onPlaying/);
assert.match(media, /onPause/);
assert.doesNotMatch(media, /media-poster is-ready/);
const data = read("lib/data.ts");
assert.match(data, /getClipMedia/);
assert.doesNotMatch(data, /interactive-examples\.mdn\.mozilla\.net/);
const copy = read("components/copy-prompt.tsx");
assert.match(copy, /navigator\.clipboard/);
assert.match(copy, /execCommand\("copy"\)/);
const search = read("components/search-surface.tsx");
assert.match(search, /Escape/);
assert.match(search, /aria-modal/);
assert.match(search, /ArrowDown/);
assert.match(search, /onKeyDown={handleKeyDown}/);
assert.match(search, /data-search-highlight/);
const saved = read("components/saved-view.tsx");
assert.match(saved, /onChange={setActive}/);
const logo = read("components/brand/HotRankLogo.tsx");
const header = read("components/header.tsx");
assert.match(logo, /\/brand\/hotrank\/v2\/hotrank-wordmark-dark-trimmed\.png/);
assert.match(logo, /\/brand\/hotrank\/v2\/hotrank-icon-pink-trimmed\.png/);
assert.match(logo, /unoptimized/);
assert.match(header, /HotRankLogo variant="primary"/);
assert.doesNotMatch(header, /hotrank-(wordmark|icon)-(complete-)?[^" ]+\.svg/);
console.log("HOTRANK targeted smoke tests passed");
