import {PromptCard} from "@/components/cards";
import {LocalTabs, FollowButton} from "@/components/interaction-controls";
import {readServerHotRank} from "@/lib/hotrank/services/server";
import type {CreatorProfileData} from "@/lib/hotrank/domain/types";
import {notFound} from "next/navigation";

export const dynamic = "force-dynamic";

export default async function CreatorProfile({params}: {params: Promise<{slug: string}>}) {
  const {slug} = await params;
  const data = await readServerHotRank("creator", slug) as CreatorProfileData | null;
  if (!data) notFound();
  return <main><div className="profile-banner" style={{backgroundImage: "linear-gradient(180deg,rgba(7,8,9,.08),#070809),url('/media/clip-landscape.png')"}}/><div className="profile-header"><img className="avatar" src={data.creator.avatar} alt={data.creator.name}/><div><h1 className="serif">{data.creator.name} <span className="pink">◆</span></h1><p style={{fontSize: 16, maxWidth: 540}}>{data.creator.bio}</p><div className="meta">⌖ {data.creator.location}</div></div><FollowButton/></div><div className="stat-row profile-stats">{[[data.creator.rankLabel || "—", "Rank"], [data.creator.followersLabel?.split(" ")[0] || "—", "Followers"], [data.creator.clipsLabel || "—", "Clips"], [data.creator.viewsLabel || "—", "Views"], [data.creator.promptsLabel || "—", "Prompts"]].map((item) => <div className="stat" key={item[1]}><strong>{item[0]}</strong><span>{item[1]}</span></div>)}</div><LocalTabs items={["OVERVIEW", "CLIPS", "PROMPTS", "WORKFLOW", "ABOUT"]} initial="OVERVIEW"/><div className="shell"><section className="profile-work"><div><div className="section-head"><h2 className="serif">Featured Work</h2><span className="view-all">View all</span></div><div className="work-grid">{data.featuredWork.map((clip) => <img key={clip.id} src={clip.poster} alt={`${clip.title} featured clip`}/>)}</div>{!data.featuredWork.length && <p className="meta">No approved clips yet.</p>}</div><div><div className="section-head"><h2 className="serif">Recent Work</h2><span className="view-all">View all</span></div><div className="work-grid">{data.recentWork.map((clip) => <img key={clip.id} src={clip.poster} alt={`${clip.title} recent clip`}/>)}</div>{!data.recentWork.length && <p className="meta">No approved clips yet.</p>}</div></section><section className="profile-lower creator-lower section"><div><div className="section-head"><h2 className="serif">Top Prompts</h2><span className="view-all">View all</span></div>{data.prompts.map((prompt) => <PromptCard key={prompt.id} prompt={prompt}/>)}{!data.prompts.length && <p className="meta">No public prompts yet.</p>}</div><div><div className="section-head"><h2 className="serif">Tools Used</h2></div><div className="card tools-panel"><div className="chips">{data.tools.map((tool) => <span className="tag" key={tool}>{tool}</span>)}</div>{!data.tools.length && <p className="meta">No tool metadata published.</p>}</div></div><div><div className="section-head"><h2 className="serif">Workflow</h2><span className="view-all">View full</span></div><div className="workflow-strip">{data.workflow.map((item, index) => <div className="workflow-step" key={item.title}><strong>{item.title}</strong><small>{item.description}</small>{index < data.workflow.length - 1 && <span aria-hidden="true">→</span>}</div>)}</div>{!data.workflow.length && <p className="meta">No public workflow metadata.</p>}</div></section></div></main>;
}
