"use client";

import {useState} from "react";
import {Tabs,ClipCard,PromptCard} from "@/components/cards";
import {imgs,savedClips} from "@/lib/data";
import {FollowButton} from "@/components/interaction-controls";

export default function Saved(){
  const [active,setActive]=useState("CLIPS");
  return <main className="shell"><div className="saved-heading"><h1 className="page-title serif">Saved</h1><div className="saved-tools"><span className="meta">432 saved items</span><button className="select" type="button">Newest saved⌄</button></div></div><Tabs onChange={setActive}/>{active==="CLIPS"&&<section><div className="section-head"><h2 className="serif">Recently Saved</h2><span className="view-all">View all　›</span></div><div className="rail saved-rail">{savedClips.map(x=><ClipCard key={x[0]} item={x} saved/>)}</div></section>}{active==="PROMPTS"&&<section><div className="section-head"><h2 className="serif">Prompt Library</h2><span className="view-all">View all　›</span></div><PromptCard image={imgs.mountain} title="Beyond the Valley" copy="Cinematic wide shot of a lone figure crossing a storm-lit valley, quiet atmosphere, realistic film texture."/><PromptCard image={imgs.city} title="City Dusk Reverie" copy="Cinematic wide shot of a woman on a rooftop at dusk, looking over a sprawling city."/></section>}{active==="COLLECTIONS"&&<section><div className="section-head"><h2 className="serif">Collections</h2><span className="view-all">View all collections　›</span></div><div className="collection-grid">{['Cinematic Concepts','Visual Storytelling','Moodboard Inspo'].map((x,i)=><div className="card collection-card" key={x}><img src={[imgs.neon,imgs.city,imgs.mountain][i]} alt={`${x} cover`}/><div><h2 className="serif">{x}</h2><div className="meta">{36+i*9} clips</div><button className="icon-btn" type="button" style={{marginTop:18}} aria-label={`Open ${x}`}><span className="pink">▮</span></button></div></div>)}</div></section>}{active==="FOLLOWING"&&<section><div className="section-head"><h2 className="serif">Creators You Follow</h2><span className="view-all">View all　›</span></div>{['Cole Bennett','Liora Avery','Chris Saunders'].map((x,i)=><div className="follow-row" key={x}><img src={[imgs.creatorCole,imgs.creatorLiora,imgs.creatorChris][i]} alt={`${x} avatar`}/><span>{x}<small className="meta" style={{display:'block'}}>Director · ranked creator</small></span><FollowButton label="Following"/></div>)}</section>}</main>;
}
