import {Flame} from "lucide-react";
import {ClipCard} from "@/components/cards";
import {AdaptiveMedia} from "@/components/adaptive-media";
import {getHomeData} from "@/lib/hotrank";

export default function Home() {
  const {hero, liveRankings, risingNow, editorPicks} = getHomeData();
  return <main className="shell"><div className="eyebrow"><span className="pink">●</span> LIVE　 <span className="muted">UPDATED 2 MINUTES AGO</span></div><div className="home-hero section"><div className="card hero-card"><AdaptiveMedia href="/clips/echoes-of-tomorrow" poster={hero.poster} video={hero.video} ratio={hero.ratio} alt="Where the Wild Still Lives landscape" label={<><div className="media-gradient"/><div className="media-caption"><h3 className="serif">{hero.title}</h3><div className="meta">{hero.creator.name}　<span className="heat"><Flame size={13}/> {hero.heat}</span>　<span className="movement up">↑ 3</span></div></div></>}/></div><div className="rank-list"><div className="rank-head"><span>Rank</span><span></span><span>Title</span><span>Heat</span><span>Move</span></div>{liveRankings.map((clip, i)=><div className="rank-item" key={clip.id}><span className="rank-num">0{i + 2}</span><img className="rank-thumb" src={clip.poster} alt={`${clip.title} thumbnail`}/><span className="rank-title">{clip.title}<small className="meta" style={{display: "block"}}>{clip.creator.name}</small></span><span className="heat">{clip.heat}</span><span className={`movement ${clip.movement.direction === "down" ? "down" : "up"}`}>{clip.movement.label}</span></div>)}<div className="rank-action">VIEW FULL RANKINGS　›</div></div></div><section className="section"><div className="section-head"><h2 className="serif">Rising now</h2><a className="view-all" href="/rankings">View all　›</a></div><div className="rail">{risingNow.map((clip) => <ClipCard key={clip.id} item={clip}/>)}</div></section><section className="section"><div className="section-head"><h2 className="serif">Editor picks</h2><a className="view-all" href="/rankings">View all　›</a></div><div className="editor-grid">{editorPicks.map((clip, i) => <ClipCard key={clip.id} item={clip} wide={i === 0} overlay/>)}</div></section></main>;
}
