export const imgs={mountain:'/media/mountain-scene-clean.png',ocean:'/media/clip-chasing-clean.png',neon:'/media/clip-electric-clean.png',portrait:'/media/creator-feature-clean.png',softChaos:'/media/clip-soft-chaos-clean.png',arctic:'/media/clip-arctic-clean.png',forest:'/media/clip-landscape.png',desert:'/media/clip-long-way-clean.png',city:'/media/clip-after-midnight-clean.png',avatar:'/media/creator-cole-clean.png',creatorFeature:'/media/creator-feature-clean.png',creatorCole:'/media/creator-cole-clean.png',creatorLiora:'/media/creator-feature-clean.png',creatorChris:'/media/creator-chris-clean.png',creatorAyo:'/media/creator-ayo-clean.png',creatorJordan:'/media/creator-jordan-clean.png',clipLandscape:'/media/clip-landscape.png',clipPortrait:'/media/clip-portrait.png',submitPreview:'/media/submit-preview.png'};
export const canonicalHero='/media/live-hero.png';
// Preview video is opt-in until a clip-specific local source exists. Correct posters remain authoritative.
export const demoVideo: string | undefined = undefined;
export const clips=[['Where the Wild Still Lives',imgs.mountain,'Wilderlens','98.7','↑ 3','16:9'],['Chasing Currents',imgs.ocean,'Oceanborn','81.4','↑ 12','16:9'],['Electric Youth',imgs.neon,'Lunak','78.9','↑ 7','4:5'],['Arctic Eyes',imgs.arctic,'Wilderlens','77.2','↑ 9','1:1'],['The Long Way Down',imgs.desert,'TrailSeeker','75.1','↑ 15','4:5'],['Soft Chaos',imgs.softChaos,'MadeByKai','74.0','↓ 3','9:16'],['After Midnight',imgs.city,'Sable','72.8','↑ 6','2.39:1'],['Concrete Dreams',imgs.forest,'Urban Souls','82.0','↑ 1','2:1']];
export const savedClips=[['The Last Horizon','/media/saved-horizon-clean.png','Mirae','98.7','↑ 1','16:9'],['Neon Reverie','/media/saved-neon-clean.png','lucidframes','81.4','↑ 4','4:5'],['Feline Whispers','/media/saved-feline-clean.png','softvisions','78.9','↑ 7','1:1'],['Cabin in the Mist','/media/saved-cabin-clean.png','nòrdika','77.2','↑ 9','4:5'],['Voidwalker','/media/saved-void-clean.png','synthedge','75.1','↑ 3','9:16']];
export const creators=[['Liora Avery',imgs.creatorLiora,'412K Followers'],['Cole Bennett',imgs.creatorCole,'1.02M Followers'],['Tate McRae',imgs.creatorAyo,'1.2M Followers'],['Chris Saunders',imgs.creatorChris,'389K Followers'],['Adara Voss',imgs.creatorLiora,'98.6K Followers']];
export function getClipMedia(title: string) {
  const clip = clips.find(item => item[0] === title);
  return clip ? {id: clip[0].toLowerCase().replace(/[^a-z0-9]+/g, "-"), poster: clip[1], video: undefined, ratio: clip[5]} : undefined;
}
