import { createClient, type SupabaseClient, type User } from '@supabase/supabase-js';
import type { Clip, Creator, Platform } from '../../types';

export type AuthGateway = { getUser(): Promise<User | null>; onAuthStateChange(callback: (user: User | null) => void): () => void; signInEmail(email: string, password: string): Promise<void>; signUpEmail(email: string, password: string): Promise<void>; signInWithGoogle(): Promise<void>; signOut(): Promise<void> };
export type RankingsRepository = { list(): Promise<Clip[]> };
export type ClipsRepository = { get(id: string): Promise<Clip | undefined> };
export type CreatorsRepository = { list(): Promise<Creator[]>; get(id: string): Promise<Creator | undefined> };
export type SavedRepository = { list(userId: string): Promise<string[]>; set(userId: string, clipId: string, saved: boolean): Promise<void> };
export type FollowRepository = { set(userId: string, creatorId: string, following: boolean): Promise<void> };
export type IgniteRepository = { set(userId: string, clipId: string, ignited: boolean): Promise<void> };
export type SubmissionRepository = { create(input: Record<string, unknown>): Promise<{ id: string }> };

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
export const hotrankConfig = { configured: Boolean(url && key), missing: [!url && 'VITE_SUPABASE_URL', !key && 'VITE_SUPABASE_ANON_KEY'].filter(Boolean) as string[] };
export const supabase: SupabaseClient | null = hotrankConfig.configured ? createClient(url!, key!) : null;
function requireClient(): SupabaseClient { if (!supabase) throw new Error(`HOTRANK backend is unavailable. Missing: ${hotrankConfig.missing.join(', ')}`); return supabase; }

type RawSubmission = { id: string; title: string | null; source_url: string; platform: string | null; embed_url: string | null; preview_thumbnail: string | null; creator_handle: string | null; canonical_url: string | null; creator_notes: string | null; submitter_id: string | null; status: string | null; created_at: string; profiles: unknown };
type CountMap = Map<string, number>;
const profileOf = (value: unknown): any => Array.isArray(value) ? value[0] || null : value || null;
const asPlatform = (value: string | null): Platform => ({ youtube: 'YouTube', twitter: 'X', x: 'X', tiktok: 'TikTok', instagram: 'Instagram' }[String(value || '').toLowerCase()] as Platform) || (['X', 'YouTube', 'TikTok', 'Instagram'].includes(value || '') ? value as Platform : 'YouTube');
const asCreator = (row: any): Creator => ({ id: row?.id || 'unknown', name: row?.display_name || row?.username || 'Anonymous creator', handle: row?.handle || row?.username || 'anonymous', avatar: row?.avatar_url || 'https://i.pravatar.cc/160?img=11', bio: row?.bio || 'A creator on HOTRANK.', followers: String(row?.followers_count || 0), rank: Number(row?.rank || 0), clips: Number(row?.clips_count || 0) });
const hashString = (value: string) => { let hash = 2166136261; for (let index = 0; index < value.length; index += 1) { hash ^= value.charCodeAt(index); hash = Math.imul(hash, 16777619); } return hash >>> 0; };
const hashedRange = (value: string, min: number, max: number) => min + (max - min) * (hashString(value) / 0xffffffff);
const bounded = (value: number) => Math.round(Math.min(100, Math.max(0, value)) * 10) / 10;
const textSignal = (value: string | null, target: number, floor: number) => { const length = value?.trim().length || 0; return length ? floor + Math.min(length, target) / target * (100 - floor) : floor; };
const heatFor = (row: RawSubmission, newestRank: number, poolSize: number) => {
  const freshness = poolSize <= 1 ? 100 : 58 + (1 - (newestRank - 1) / (poolSize - 1)) * 42;
  const velocity = hashedRange(`${row.id}:${row.created_at}:${row.embed_url || row.source_url || ''}`, 48, 100);
  const content = (row.preview_thumbnail ? 36 : 0) + (row.embed_url || row.canonical_url ? 28 : 0) + (row.platform ? 18 : 0) + textSignal(row.creator_notes, 180, 36) * .28 + textSignal(row.embed_url || row.source_url, 120, 42) * .18;
  const creator = (row.submitter_id ? 76 : 38) * .7 + hashedRange(`${row.submitter_id || 'unknown'}:${row.creator_handle || '@anonymous'}`, 46, 100) * .3;
  return bounded(freshness * .24 + velocity * .34 + content * .24 + creator * .18);
};
const asClip = (row: RawSubmission, rank: number, heat: number, saves: number, ignites: number, movement: 'up' | 'down' | 'flat'): Clip => { const creator = asCreator(profileOf(row.profiles)); return { id: row.id, title: row.title?.trim() || 'Untitled submission', creator, image: row.preview_thumbnail || '', rank, heat, movement, change: 0, category: 'User Submitted', platform: asPlatform(row.platform), duration: '00:00', description: row.creator_notes || '', why: row.creator_notes || 'Ranking rationale is still being gathered.', tags: row.platform ? [row.platform] : [], saves: String(saves), shares: '0', views: '0' }; };

async function counts(table: 'saves' | 'ignites', ids: string[]): Promise<CountMap> { if (!ids.length) return new Map(); const { data, error } = await requireClient().from(table).select('submission_id').in('submission_id', ids); if (error) throw error; return (data || []).reduce((map, row) => map.set(row.submission_id, (map.get(row.submission_id) || 0) + 1), new Map<string, number>()); }
async function fetchRows(id?: string): Promise<RawSubmission[]> { let query = requireClient().from('submissions').select('id,title,source_url,platform,embed_url,preview_thumbnail,creator_handle,canonical_url,creator_notes,submitter_id,status,created_at,profiles!submissions_submitter_id_fkey(id,username,display_name,handle,avatar_url,bio)'); query = id ? query.eq('id', id) : query.in('status', ['pending', 'approved']).order('created_at', { ascending: false }).order('id', { ascending: false }); const { data, error } = id ? await query.maybeSingle() : await query; if (error) throw error; return (id ? (data ? [data] : []) : data || []) as RawSubmission[]; }
async function rankRows(rows: RawSubmission[]): Promise<Clip[]> { const saveCounts = await counts('saves', rows.map((row) => row.id)); const igniteCounts = await counts('ignites', rows.map((row) => row.id)); const pending = rows.filter((row) => row.status === 'pending').map((row, index) => asClip(row, index + 1, 0, saveCounts.get(row.id) || 0, igniteCounts.get(row.id) || 0, 'flat')); const approvedNewest = rows.filter((row) => row.status === 'approved'); const newestRank = new Map(approvedNewest.map((row, index) => [row.id, index + 1])); return [...pending, ...approvedNewest.map((row) => ({ row, heat: heatFor(row, newestRank.get(row.id) || 1, approvedNewest.length) })).sort((a, b) => b.heat - a.heat || b.row.created_at.localeCompare(a.row.created_at)).map(({ row, heat }, index) => { const previous = newestRank.get(row.id) || index + 1; const current = index + 1; return asClip(row, current, heat, saveCounts.get(row.id) || 0, igniteCounts.get(row.id) || 0, current < previous ? 'up' : current > previous ? 'down' : 'flat'); })]; }

export const rankingsRepository: RankingsRepository = { async list() { return rankRows(await fetchRows()); } };
export const clipsRepository: ClipsRepository = { async get(id) { const rows = await fetchRows(id); if (!rows[0]) return undefined; const ranked = await rankRows(rows); return ranked[0]; } };
export const creatorsRepository: CreatorsRepository = { async list() { const { data, error } = await requireClient().from('profiles').select('*').order('created_at', { ascending: false }).limit(50); if (error) throw error; return (data || []).map(asCreator); }, async get(id) { const { data, error } = await requireClient().from('profiles').select('*').eq('id', id).maybeSingle(); if (error) throw error; return data ? asCreator(data) : undefined; } };
export const authGateway: AuthGateway = { async getUser() { const { data, error } = await requireClient().auth.getUser(); return error ? null : data.user; }, onAuthStateChange(callback) { const { data } = requireClient().auth.onAuthStateChange((_event, session) => callback(session?.user || null)); return () => data.subscription.unsubscribe(); }, async signInEmail(email, password) { const { error } = await requireClient().auth.signInWithPassword({ email, password }); if (error) throw error; }, async signUpEmail(email, password) { const { error } = await requireClient().auth.signUp({ email, password, options: { emailRedirectTo: window.location.origin } }); if (error) throw error; }, async signInWithGoogle() { const { error } = await requireClient().auth.signInWithOAuth({ provider: 'google', options: { redirectTo: `${window.location.origin}/` } }); if (error) throw error; }, async signOut() { const { error } = await requireClient().auth.signOut(); if (error) throw error; } };
export const savedRepository: SavedRepository = { async list(userId) { const { data, error } = await requireClient().from('saves').select('submission_id').eq('user_id', userId); if (error) throw error; return (data || []).map((row) => row.submission_id); }, async set(userId, clipId, saved) { const response = saved ? await requireClient().from('saves').upsert({ user_id: userId, submission_id: clipId }) : await requireClient().from('saves').delete().eq('user_id', userId).eq('submission_id', clipId); if (response.error) throw response.error; } };
export const followRepository: FollowRepository = { async set(userId, creatorId, following) { const response = following ? await requireClient().from('follows').upsert({ follower_id: userId, following_id: creatorId }) : await requireClient().from('follows').delete().eq('follower_id', userId).eq('following_id', creatorId); if (response.error) throw response.error; } };
export const igniteRepository: IgniteRepository = { async set(userId, clipId, ignited) { const response = ignited ? await requireClient().from('ignites').upsert({ user_id: userId, submission_id: clipId }) : await requireClient().from('ignites').delete().eq('user_id', userId).eq('submission_id', clipId); if (response.error) throw response.error; } };
export const submissionRepository: SubmissionRepository = { async create(input) { const { data, error } = await requireClient().from('submissions').insert(input).select('id').single(); if (error) throw error; return data; } };
