import Link from "next/link";
import {Flame} from "lucide-react";
import {readServerHotRank} from "@/lib/hotrank/services/server";
import type {RankingsData} from "@/lib/hotrank/domain/types";

export const dynamic = "force-dynamic";

export default async function Rankings() {
  const {featured, rows} = await readServerHotRank("rankings") as RankingsData;
  return <main className="shell"><div className="filterbar">{[["category", "Category", "All Categories"], ["range", "Time range", "Last 7 Days"], ["format", "Format", "All Formats"], ["length", "Length", "Any Length"], ["heat", "Heat threshold", "Medium"]].map(([id, label, value]) => <label className="filter-field" key={id}><span className="label">{label}</span><select id={id} className="select" defaultValue={value}><option>{value}</option><option>All</option></select></label>)}<button className="btn" type="button">Clear</button><button className="btn primary" type="button">Apply Filters</button></div>{!featured.length && !rows.length && <p className="meta" style={{marginTop: 24}}>No ranked clips yet.</p>}<div className="featured-ranks">{featured.map((entry) => <Link href={`/clips/${entry.clip.slug}`} className={`card featured-rank ${entry.rankPosition === 1 ? "featured-rank-main" : ""}`} key={entry.id}><div className="media"><img src={entry.clip.poster} alt={`${entry.clip.title} featured media`}/><span className="tag format-tag">{entry.clip.ratio}</span></div><div><span className={`rank-badge rank-${entry.rankPosition}`}>{entry.rankPosition}</span><h2 className="serif">{entry.clip.title}</h2><div>{entry.clip.creator.name} ◆</div><p className="meta">{entry.reason}</p><div className="heat" style={{marginTop: 18}}>HEAT {entry.clip.heat} <Flame size={14}/></div></div></Link>)}</div><div className="ranking-content"><div className="table"><div className="table-row head"><span>#</span><span>Title</span><span>Creator</span><span>Why trending</span><span>Heat</span><span>Saves</span><span>Movement</span></div>{rows.map((entry) => <Link href={`/clips/${entry.clip.slug}`} className="table-row" key={entry.id}><span className="rank-num">{String(entry.rankPosition).padStart(2, "0")}</span><span className="table-title"><img className="table-thumb" src={entry.clip.poster} alt={`${entry.clip.title} thumbnail`}/>{entry.clip.title}</span><span>{entry.clip.creator.name} ◆</span><span className="muted">{entry.reason}</span><span className="heat">{entry.clip.heat} <Flame size={12}/></span><span>{entry.savesLabel}</span><span className={entry.movement.direction === "down" ? "movement down" : "movement up"}>{entry.movement.label}</span></Link>)}</div><aside className="side-stack"><div className="side-box"><h3>⌁ FASTEST RISING <span className="view-all">View All</span></h3>{rows.slice(4, 9).map((entry, index) => <div className="mini-row" key={entry.id}><span>{index + 1}</span><img src={entry.clip.poster} alt={`${entry.clip.title} thumbnail`}/><span className="serif">{entry.clip.title}</span><strong>{entry.movement.label}</strong></div>)}</div><div className="side-box"><h3>♡ MOST SAVED <span className="view-all">View All</span></h3>{rows.slice(0, 5).map((entry, index) => <div className="mini-row" key={entry.id}><span>{index + 1}</span><span className="serif">{entry.clip.title}</span><span>{entry.savesLabel}</span></div>)}</div></aside></div></main>;
}
